In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(['id','Unnamed: 32'], axis=1, inplace=True)

In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [ ]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)


In [ ]:
# scaling: adjusts values to similar range

scaler = StandardScaler()

# computes the mean and std form training data
# Then transforms training data
x_train = scaler.fit_transform(X_train)
# never use .fit() on test data — it would "leak" information from test set into training.
x_test = scaler.transform(X_test)

In [ ]:
x_train

array([[-0.78175789, -0.40759827, -0.79951689, ..., -0.43016904,
         0.11044882, -0.36659098],
       [-0.09413421, -0.82608898, -0.06598358, ...,  0.35282704,
        -0.4990587 ,  1.02449327],
       [-0.89448308, -0.39584291, -0.86902674, ..., -0.25272858,
        -0.97523645, -0.07639611],
       ...,
       [ 0.24122324,  1.3862692 ,  0.14295484, ..., -1.3149302 ,
        -2.12441208, -1.58671615],
       [ 0.24404137, -0.89191898,  0.22105119, ...,  0.34672419,
         0.08029089, -0.03066183],
       [ 1.67846946,  1.07122564,  1.74413458, ...,  1.17671225,
         0.61995901,  0.5720506 ]])

In [ ]:
y_train
# Theh y_train contains alphabetical chars so our neural network won't
# be able to recognize it. So we've to encode it using LabelEncoder()

410    B
73     M
534    B
123    B
65     M
      ..
419    B
95     M
38     M
227    B
302    M
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,

In [50]:
# convert numpy arrays to tensors
X_train_tensor = torch.from_numpy(x_train)
X_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [51]:
X_train_tensor

tensor([[-0.7818, -0.4076, -0.7995,  ..., -0.4302,  0.1104, -0.3666],
        [-0.0941, -0.8261, -0.0660,  ...,  0.3528, -0.4991,  1.0245],
        [-0.8945, -0.3958, -0.8690,  ..., -0.2527, -0.9752, -0.0764],
        ...,
        [ 0.2412,  1.3863,  0.1430,  ..., -1.3149, -2.1244, -1.5867],
        [ 0.2440, -0.8919,  0.2211,  ...,  0.3467,  0.0803, -0.0307],
        [ 1.6785,  1.0712,  1.7441,  ...,  1.1767,  0.6200,  0.5721]],
       dtype=torch.float64)

Defining The model

In [62]:
class MySimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  # binary cross entropy loss
  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log 0
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # calculate loss: Binary Cross Entropy Loss
    Loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred))
    return Loss.mean()


Important Params

In [68]:
learning_rate = 0.1 # learning rate (α) used in gradient descent optimization.
epochs = 25 # model will go through the full dataset 25 times during training.

# First few passes: model learns rough patterns
# Later passes: model fine-tunes weights
# Too many: risk of overfitting (memorizing data)
# Too few: underfitting (not learning enough)

In [69]:
# # create model
# model = MySimpleNN(X_train_tensor)
# model.weights # shape -> 30, 1

In [55]:
# model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

Model Training Pipeline

In [71]:
# define model
model = MySimpleNN(X_train_tensor)

# define loop (for epochs times)
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)
  # print(y_pred)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)
  # print(f"Epoch: {epoch + 1} Loss: {loss.item()}")

  # backward pass
  loss.backward()

  # parameters update (don't track the gradients for weights and bias calculations)
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad # dL/dW = model.weights.grad
    model.bias -= learning_rate * model.bias.grad # dL/db = model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epochs
  print(f"Epoch: {epoch + 1} Loss: {loss.item()}")

Epoch: 1 Loss: 2.939527122933425
Epoch: 2 Loss: 2.7833506163613624
Epoch: 3 Loss: 2.6209844080971063
Epoch: 4 Loss: 2.451266009090371
Epoch: 5 Loss: 2.2768180483064966
Epoch: 6 Loss: 2.1010303519032
Epoch: 7 Loss: 1.9303326223242834
Epoch: 8 Loss: 1.766099722441049
Epoch: 9 Loss: 1.611610131177511
Epoch: 10 Loss: 1.4637022712985945
Epoch: 11 Loss: 1.3269408484538092
Epoch: 12 Loss: 1.2069431277385707
Epoch: 13 Loss: 1.1053265031811204
Epoch: 14 Loss: 1.0227476203676866
Epoch: 15 Loss: 0.9585012065119617
Epoch: 16 Loss: 0.910436833592791
Epoch: 17 Loss: 0.8753506334093731
Epoch: 18 Loss: 0.8497472635180098
Epoch: 19 Loss: 0.8305951327756659
Epoch: 20 Loss: 0.8156819871704996
Epoch: 21 Loss: 0.8035609127858204
Epoch: 22 Loss: 0.7933358846380997
Epoch: 23 Loss: 0.7844610284438823
Epoch: 24 Loss: 0.7766005203819456
Epoch: 25 Loss: 0.7695415662863406


In [72]:
model.weights

tensor([[-0.1340],
        [ 0.1134],
        [ 0.0565],
        [ 0.0061],
        [ 0.0549],
        [-0.1224],
        [ 0.1078],
        [-0.3434],
        [ 0.4400],
        [-0.1939],
        [-0.2577],
        [-0.0938],
        [-0.0663],
        [-0.0919],
        [ 0.1136],
        [ 0.1718],
        [-0.2102],
        [ 0.2023],
        [ 0.4273],
        [ 0.4557],
        [-0.0836],
        [ 0.2111],
        [ 0.5680],
        [ 0.4053],
        [ 0.0184],
        [-0.1927],
        [-0.2246],
        [-0.3893],
        [ 0.1964],
        [-0.1330]], dtype=torch.float64, requires_grad=True)

In [73]:
model.bias

tensor([-0.1705], dtype=torch.float64, requires_grad=True)

Evaluation

In [89]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.99).float()
  # print(y_pred)
  # print(y_test_tensor)
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.640350878238678
