In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
  print("GPU is Available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not Availble, Using CPU")

GPU is Available
Using GPU: Tesla T4


In [6]:
# creating a Tensor
t = torch.empty(2, 3)

In [7]:
# check type
type(t)

torch.Tensor

In [8]:
# using zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.rand(2, 3)

tensor([[0.6446, 0.0082, 0.5724],
        [0.3417, 0.3996, 0.4358]])

In [14]:
# manual seed
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
# custom tensor
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [18]:
# linearly spaced
torch.linspace(0, 10, 10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [19]:
# identity matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [20]:
torch.full((3, 3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [21]:
# Tensor Shapes

x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x.shape

torch.Size([2, 3])

In [25]:
torch.empty_like(x)

tensor([[1172137984037307205, 5928235795676664320, 5495026351378022729],
        [5912955912783466565, 5495026325473546309,  148693834829815621]])

In [26]:
torch.zeros_like(x)
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [32]:
torch.rand_like(x, dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [29]:
# find data type of tensor
x.dtype

torch.int64

In [30]:
# specifying dtype of tensor while creating
torch.tensor([1.0, 2.0, 3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [31]:
# convrting dtype
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [33]:
# Mathematical Ops on Tensors

# scalar ops
y = torch.rand(2, 2)
y

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [40]:
print(y + 2)
print(y - 2)
print(y * 2)
print(y / 2)
print(((y * 100) // 3) % 2)
print(x ** 2)

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])
tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])
tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])
tensor([[0.3559, 0.3938],
        [0.2092, 0.4507]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [41]:
# element wise operation in more than one tensor

a = torch.rand(2, 3)
b = torch.rand(2, 3)
print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [43]:
# add
print(a + b)
# sub
print(a - b)
# mul
print(a * b)
# div
print(a / b)

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])
tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])
tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])
tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])


In [50]:
# abs
c = torch.tensor([1, -2, 3, -42])
print(torch.abs(c))

# negative
print(torch.neg(c))

# round
print(torch.round(torch.tensor([1.2, 1.5, 1.8])))

# ceil
print(torch.ceil(torch.tensor([1.2, 1.5, 1.8])))

# floor
print(torch.floor(torch.tensor([1.2, 1.5, 1.8])))

# clamp
print(torch.clamp(torch.tensor([1, 2, 3, 4, 5]), min = 2, max = 4))

tensor([ 1,  2,  3, 42])
tensor([-1,  2, -3, 42])
tensor([1., 2., 2.])
tensor([2., 2., 2.])
tensor([1., 1., 1.])
tensor([2, 2, 3, 4, 4])


In [58]:
# reduction operation

x = torch.randint(size = (2, 3), low = 0, high = 10, dtype= torch.float32)
print(x)

tensor([[5., 7., 5.],
        [9., 9., 7.]])


In [53]:
torch.sum(x)

tensor(28)

In [61]:
torch.sum(x, dim = 0) # column sum
torch.sum(x, dim = 1) # row sum

# mean
print(torch.mean(x))
print(torch.mean(x, dim = 0))
print(torch.mean(x, dim = 1))

# median
print(torch.median(x))
print(torch.median(x, dim = 0))
print(torch.median(x, dim = 1))

tensor(7.)
tensor([7., 8., 6.])
tensor([5.6667, 8.3333])
tensor(7.)
torch.return_types.median(
values=tensor([5., 7., 5.]),
indices=tensor([0, 0, 0]))
torch.return_types.median(
values=tensor([5., 9.]),
indices=tensor([2, 0]))


In [67]:
torch.max(x)
torch.max(x, dim = 0)
torch.max(x, dim = 1)

torch.min(x)
torch.min(x, dim = 0)
torch.min(x, dim = 1)


# product of the tensor
torch.prod(x)

# standard deviation
torch.std(x)

tensor(1.7889)

In [69]:
# variance
torch.var(x)

tensor(3.2000)

In [71]:
torch.argmax(x)

torch.argmin(x)

tensor(0)

In [72]:
# Matrix Operations

e = torch.randint(size = (2, 3), low=0, high=10)
f = torch.randint(size = (3, 2), low=0, high=10)
print(e)
print(f)

tensor([[5, 9, 8],
        [9, 7, 9]])
tensor([[2, 6],
        [7, 7],
        [8, 3]])


In [75]:
# matrix multiplication
torch.mm(e, f)

tensor([[137, 117],
        [139, 130]])

In [76]:
# dot product
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([4, 5, 6])
torch.dot(v1, v2)

tensor(32)

In [78]:
print(e)

# transpose
torch.transpose(e, 0, 1)

tensor([[5, 9, 8],
        [9, 7, 9]])


tensor([[5, 9],
        [9, 7],
        [8, 9]])

In [85]:
g = torch.randint(size = (3, 3), low=0, high=10, dtype = torch.float32)
print(g)

# determinant [for square matrix]
print(torch.det(g))

# inverse [for square matrix]
print(torch.inverse(g))

tensor([[6., 6., 8.],
        [4., 9., 0.],
        [7., 9., 2.]])
tensor(-156.)
tensor([[-0.1154, -0.3846,  0.4615],
        [ 0.0513,  0.2821, -0.2051],
        [ 0.1731,  0.0769, -0.1923]])


In [91]:
# comparison operations

i = torch.randint(size = (2, 3), low=0, high=10)
j = torch.randint(size = (2, 3), low=0, high=10)
print(i)
print(j)

tensor([[2, 3, 7],
        [0, 2, 5]])
tensor([[2, 8, 0],
        [2, 5, 3]])


In [94]:
# comparisons

i >= j

i <= j

i == j

i != j

tensor([[False,  True,  True],
        [ True,  True,  True]])

In [104]:
k = torch.randint(size = (2, 3), low=0, high=10, dtype=torch.float32)
print(k)

tensor([[2., 7., 9.],
        [3., 9., 7.]])


In [106]:
# log
print(torch.log(k))

# exponent
print(torch.exp(k))

# sqrt
print(torch.sqrt(k))

# sigmoid
print(torch.sigmoid(k))

# softmax
print(torch.softmax(k, dim=0))

# relu
print(torch.relu(k))

tensor([[0.6931, 1.9459, 2.1972],
        [1.0986, 2.1972, 1.9459]])
tensor([[7.3891e+00, 1.0966e+03, 8.1031e+03],
        [2.0086e+01, 8.1031e+03, 1.0966e+03]])
tensor([[1.4142, 2.6458, 3.0000],
        [1.7321, 3.0000, 2.6458]])
tensor([[0.8808, 0.9991, 0.9999],
        [0.9526, 0.9999, 0.9991]])
tensor([[0.2689, 0.1192, 0.8808],
        [0.7311, 0.8808, 0.1192]])
tensor([[2., 7., 9.],
        [3., 9., 7.]])


In [108]:
# Inplace Operations

m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(m)
print(n)

tensor([[0.4947, 0.3617, 0.9687],
        [0.0359, 0.3041, 0.9867]])
tensor([[0.1290, 0.6887, 0.1637],
        [0.0899, 0.3139, 0.1219]])


In [109]:
m.add_(n)

tensor([[0.6237, 1.0504, 1.1323],
        [0.1258, 0.6180, 1.1086]])

In [110]:
m

tensor([[0.6237, 1.0504, 1.1323],
        [0.1258, 0.6180, 1.1086]])

In [111]:
m.relu_()

tensor([[0.6237, 1.0504, 1.1323],
        [0.1258, 0.6180, 1.1086]])

In [112]:
# copying a tensor
a = torch.rand(2, 3)
a

tensor([[0.3516, 0.2316, 0.2847],
        [0.3520, 0.2828, 0.2420]])

In [115]:
b = a
b

tensor([[0.3516, 0.2316, 0.2847],
        [0.3520, 0.2828, 0.2420]])

In [119]:
id(a) == id(b) # same memory location

True

In [120]:
b = a.clone()

In [122]:
id(a) == id(b) # after cloning different memory locations

False

In [123]:
# Tensor operations on GPU

torch.cuda.is_available()

True

In [124]:
device = torch.device('cuda')

In [126]:
# creating tensor on GPU

torch.rand((2, 3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [128]:
# moving existing tensor to GPU

b = a.to(device)

tensor([[0.3516, 0.2316, 0.2847],
        [0.3520, 0.2828, 0.2420]], device='cuda:0')

In [129]:
b + 5

tensor([[5.3516, 5.2316, 5.2847],
        [5.3520, 5.2828, 5.2420]])

In [130]:
import time

size = 10000

matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
end_time = time.time()

print(f"CPU time: {end_time - start_time}")

matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()
end_time = time.time()

print(f"GPU time: {end_time - start_time}")

CPU time: 24.24071717262268
GPU time: 0.6816599369049072


In [134]:
# Reshaping Tensors

a = torch.eye(4, 4)
a

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [135]:
a.reshape(2, 2, 2, 2)

tensor([[[[1., 0.],
          [0., 0.]],

         [[0., 1.],
          [0., 0.]]],


        [[[0., 0.],
          [1., 0.]],

         [[0., 0.],
          [0., 1.]]]])

In [136]:
# flatten

a.flatten()

tensor([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [137]:
# permute

b = torch.rand(2, 3, 4)
b

tensor([[[0.8673, 0.1561, 0.3627, 0.4080],
         [0.0238, 0.9556, 0.0546, 0.9876],
         [0.7779, 0.1610, 0.0409, 0.2777]],

        [[0.5977, 0.7007, 0.1637, 0.3872],
         [0.8402, 0.1092, 0.4046, 0.3539],
         [0.5803, 0.0621, 0.3397, 0.2102]]])

In [138]:
b.permute(2, 0, 1)

tensor([[[0.8673, 0.0238, 0.7779],
         [0.5977, 0.8402, 0.5803]],

        [[0.1561, 0.9556, 0.1610],
         [0.7007, 0.1092, 0.0621]],

        [[0.3627, 0.0546, 0.0409],
         [0.1637, 0.4046, 0.3397]],

        [[0.4080, 0.9876, 0.2777],
         [0.3872, 0.3539, 0.2102]]])

In [140]:
# unsqueeze

# image size
c = torch.rand(226, 226, 3)
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [146]:
# squeeze
d = torch.rand(1, 20)
d
d.squeeze(0)

tensor([0.9009, 0.5502, 0.7036, 0.8452, 0.8943, 0.0686, 0.8604, 0.7327, 0.6850,
        0.1864, 0.6581, 0.2685, 0.0825, 0.2583, 0.0634, 0.4233, 0.7368, 0.1632,
        0.0485, 0.6772])

In [1]:
# numpy and pytorch
import numpy as np